---
- name: Actualizar todos los paquetes en el servidor
  hosts: all
  gather_facts: false

  tasks:
    - name: Actualizar todos los paquetes con Chocolatey
      win_chocolatey:
        name: all
        state: latest